### ISSUE TITLE
Add keyboard shortcut option to show/hide menu bar player

### ISSUE THREAD

**Issue by yougotwill** [martinfekete10/Tuneful#106]
As described above like how you can toggle the mini player visibility, it would be great to have the same for the menu bar / control center player. 

Thanks for creating this awesome piece of tech 🙏

**Comment by martinfekete10** [comment]
Good suggestion, I'll implement it and deploy in this week's release :)

**Comment by martinfekete10** [comment]
Just released a new version with this feature implemented 🎉

**Comment by yougotwill** [comment]
@martinfekete10 You are a legend! Thanks 🙏

**Comment by yougotwill** [comment]
@martinfekete10 I tried mapping the shortcut but it doesn't seem to work correctly. 

https://github.com/user-attachments/assets/4b10eb58-6e95-4cb5-aee4-0d93f931f933

**Comment by martinfekete10** [comment]
To me it seems to be working fine, I can see that Tuneful icon appears and disappears with shortcut, works the same way on my machine as well

**Comment by yougotwill** [comment]
Ah I see where my explanation went wrong. Sorry, what I meant was to be able to toggle this widget (see screenshot) with a shortcut please? 🙏

<img width="278" alt="Screenshot 2024-09-27 at 08 19 06" src="https://github.com/user-attachments/assets/c3f3e86c-0c9d-4d4c-bfac-c3cb16bc5748">
