### ISSUE TITLE
Change "add to favorites" button location in popover

### ISSUE THREAD

**Issue by upstroke-version** [martinfekete10/Tuneful#111]
I really enjoy using tuneful and I'm grateful that this app is open source, but I have a minor gripe.
When user sets popover style to minimal, and hovers cursor over the popover, "add to favorites" button and media control buttons overlaps. This doesn’t look good and sometimes causes misclicks. It would be great if the "add to favorites" button could be moved to a different location, at least when popover style is set to minimal. Maybe top left...? Slightly above from center of album art could work too.
![1](https://github.com/user-attachments/assets/44c2810a-e589-4b65-9e00-d0a5832373d4)

**Comment by martinfekete10** [comment]
It will be fixed in the next release (I moved it a bit up), thanks for reporting

**Comment by martinfekete10** [comment]
Just released a new version of Tuneful with this fix implemented
