### ISSUE TITLE
Maybe change media control icons to what Apple apps use?

### ISSUE THREAD

**Issue by upstroke-version** [martinfekete10/Tuneful#112]
I know that this is a matter of personal preference, so I can understand if you decline this request.
But personally, I think changing current media control icons to what Apple Music uses would give Tuneful  more "native app" feel.
What tuneful uses currently does not match with Apple Music's control icons.
![2](https://github.com/user-attachments/assets/9ce28a47-2eb3-4c06-b420-fe94b4225ea8)
[Apple Music]

![1](https://github.com/user-attachments/assets/b1e34ef3-7c63-44d9-bcd9-618369de55b8)
[Tuneful]

It looks like Apple uses SF Symbols on them. Each one would be
![backward fill](https://github.com/user-attachments/assets/98ea53e7-0132-4158-83f7-5927818a4b5d)
"backward.fill"
![play fill](https://github.com/user-attachments/assets/00d7d7f2-6cfb-4278-bb6a-297cb93e9ade)
"play.fill"
![forward fill](https://github.com/user-attachments/assets/60ff2af9-bbf5-42ee-978c-9968648f0946)
"forward.fill" 

It seems like Tuneful also uses SF symbols like "pause.circle.fill", but In my opinion, current selection of icons are too complex and busy, Its combination of so many shapes, circle, triangles, and bars. SF symbols used by Apple music looks better to me.

**Comment by martinfekete10** [comment]
Agree with you on this one. Currently working on a rework of these icons in both popovers and mini players; I'm also adding animations for mouse hover which should add even more native feel. This will be a part of the next release

**Comment by martinfekete10** [comment]
Just released a new version of Tuneful with this suggestion implemented
