### ISSUE TITLE
an old one issue and now a new one ver 1.6.6

### ISSUE THREAD

**Issue by JohnnyFireOne** [martinfekete10/Tuneful#114]
@martinfekete10 
still have the icon even i disable it and i quit apple music, from the settings i make the proper config but stil...
![SCR-20241012-oyci](https://github.com/user-attachments/assets/01388cb4-f063-4e03-be7b-2963ac06b72a)
![SCR-20241012-oyer](https://github.com/user-attachments/assets/77887575-e28d-4bdb-a848-561da41ef5b6)

beside that a new issue comes when i disable the popover and i click to the text title-artist this error comes out
![SCR-20241012-oxwv](https://github.com/user-attachments/assets/6128c376-3e48-46fc-a89e-d75c8125c1a5)
![SCR-20241012-oygg](https://github.com/user-attachments/assets/4ba97b73-aab7-4876-83d5-59e9277dc387)

**Comment by martinfekete10** [comment]
Ah I see what you mean by the menu bar icon behaviour - will try to find a fix for it and for the other error as well

**Comment by JohnnyFireOne** [comment]
> Ah I see what you mean by the menu bar icon behaviour - will try to find a fix for it and for the other error as well

@martinfekete10 
i choose the icon to be hidden and it is but when i quit apple music the icon of the app re appears

**Comment by martinfekete10** [comment]
Just published a new version! Both issues should be fixed now

**Comment by JohnnyFireOne** [comment]
> Just published a new version! Both issues should be fixed now

@martinfekete10 

a sweet!!!!!!! beauty all fixed!!!!!!! thank you!

**Comment by JohnnyFireOne** [comment]
@martinfekete10

a sweet!!!!!!! beauty all fixed!!!!!!! thank you!
