### ISSUE TITLE
Light mode doesn't switch to dark play buttons

### ISSUE THREAD

**Issue by VisualisationExpo** [martinfekete10/Tuneful#116]
Tuneful 1.6.7 doesn't automatically switch to dark button appearance while using Light mode in macOS. 
Just like it switches to light button appearance in dark mode in macOS. See the screenshots.

macOS is Sequoia 15.0.1 on 2023 Mac mini M2 and 8 GB RAM

Example. Light mode
<img width="236" alt="Screenshot 2024-10-13 at 12 08 16" src="https://github.com/user-attachments/assets/354adc87-a1cf-439a-bceb-f28aec34d0c1">

Example for Dark mode.
<img width="236" alt="Screenshot 2024-10-13 at 12 10 56" src="https://github.com/user-attachments/assets/abc68ce8-6ed5-4570-b7b3-bc13edd8e839">

Also, I wish that you'd include the button style for play, back and forward from somewhere around Tuneful 1.6.3 - it had a better look IMO..

**Comment by martinfekete10** [comment]
I will fix the light-mode issue in the next release, thanks for heads up. Regarding new buttons - decided to make this change to make the design more native. Same buttons are used in other places both in macOS and iOS

**Comment by VisualisationExpo** [comment]
> I will fix the light-mode issue in the next release, thanks for heads up. Regarding new buttons - decided to make this change to make the design more native. Same buttons are used in other places both in macOS and iOS

Thank you for looking into the dark/light mode issue..

too bad about the buttons, but totally understand 🙂

**Comment by VisualisationExpo** [comment]
Not even a back drop behind the buttons? Doesn't macOS have anything to help there?

**Comment by martinfekete10** [comment]
It does, it's already fixed on development branch and will be a part of the next release - which contains a lot new features so it takes a bit more time. Expecting to release it in next few days

**Comment by martinfekete10** [comment]
Fixed in the newest version v1.7.0 🎉
