### ISSUE TITLE
"Dynamic Island" improvement

### ISSUE THREAD

**Issue by rennaMAhcuS** [martinfekete10/Tuneful#123]
The new **"dynamic island"** type of song display is excellent, but it would be better if we had some **more details** like the **song name, artist name**, and others...

<img width="302" alt="image" src="https://github.com/user-attachments/assets/3a9846a6-5b33-4183-b019-fe313188af20">

**Comment by martinfekete10** [comment]
This is weird, because dynamic island notification actually contains the things that you mentioned:
<img width="511" alt="image" src="https://github.com/user-attachments/assets/a1bf4f41-cc7b-47b9-9983-fa7737de0fc5">

What macOS and Mac are you running?

**Comment by rennaMAhcuS** [comment]
I am using a **M2-Pro** MacBook Pro, **macOS** `15.1 (24B83)`.

**Comment by rennaMAhcuS** [comment]
I realized what the Issue is - **I use light mode**. If I switch to **dark mode**, it is **working**. Can you please make it compatible with light mode, too?? (**Hardcoding the color of the font to white should work**, I guess @martinfekete10)

**Comment by rennaMAhcuS** [comment]
Also, consider **updating Tuneful** on homebrew 🍺 (it **downloads version 1.6 by default**)...

**Comment by tails618** [comment]
+1. Same issue, switching to dark mode fixes it. I'm on macOS 15.2 beta.

**Comment by martinfekete10** [comment]
Just released a new v1.7.1 with this issue fixed 🎉 Let me know if there is anything else
