### ISSUE TITLE
[Bug] TuneFul Crashes if Spotify app is not installed

### ISSUE THREAD

**Issue by asboy2035** [martinfekete10/Tuneful#129]
[macOS 15.2, MacBook Pro M3 Pro]
Tuneful app crashes on launch. Installing Spotify fixes the issue.
<img width="804" alt="SCR-20241120-rkzx" src="https://github.com/user-attachments/assets/75d6531b-097c-47bc-a2e4-f8fd05a17d86">
^ This line gets the "Fatal error: Unexpectedly found nil while unwrapping an Optional value" when running without Spotify installed

**Comment by martinfekete10** [comment]
Fixed in the new release, thanks for pointing this out!

**Comment by asboy2035** [comment]
> Fixed in the new release, thanks for pointing this out!

Thank you! Great app you've got, keep up the good work! ❤️
