### ISSUE TITLE
Cant open tuneful app

### ISSUE THREAD

**Issue by gittyuphorsie** [martinfekete10/Tuneful#135]
Hi I have this issue now where I can't open the tuneful app or access the app settings. When I open from applications folder nothing happens, its no longer in the menu bar and I also disabled the mini player. The only instance where I can tell its still running is the notch animation when I switch songs in Spotify and it also keeps force restarting Spotify every time I quit the app

**Comment by martinfekete10** [comment]
Hi, what version of Tuneful are you using?

**Comment by gittyuphorsie** [comment]
It’s the latest version, I’ve also tried reinstalling it but same issue so I suspect maybe it’s something I’ve toggled in the settings? But I can’t get into the settings anymore to check

**Comment by martinfekete10** [comment]
Try removing Tuneful using [Pearcleaner](https://github.com/alienator88/Pearcleaner) and reinstalling, this will delete saved settings as well (.plist file)

**Comment by gittyuphorsie** [comment]
hello I just tried doing that and once I reinstalled tuneful and opened it, it just automatically reopened Spotify and then went back to the same issue where it keeps restarting Spotify when I quit Spotify. I then tried uninstalling Spotify altogether but when I now try to open up Tuneful nothing happens. I just can't seem to get back into the tuneful settings menu.... really struggling to figure it out

**Comment by mrtysn** [comment]
+1 to both issues. I'm running version 1.7.1 on MacOS Sonoma 14.7.1
- Launching immediately crashes the app, I've never used it with Apple Music but the frozen UI shows Apple Music related text. I also have https://github.com/tombonez/noTunes installed, so don't know whether they are colliding. (it's an app that prevents applemusic itunes from loading)
- Quitting Spotify immediately restarts Spotify until Tuneful is force killed through Activity Monitor

**Comment by gittyuphorsie** [comment]
hello I wanted to let you know the issue seems to be fixed now after I downloaded the zip file V0.9.0 that you linked in issue #140. I'm now able to access the Tuneful settings again, and Spotify doesn't restart automatically when I quit it anymore so all fixed, thank you!

**Comment by DownFall1984** [comment]
> hello I wanted to let you know the issue seems to be fixed now after I downloaded the zip file V0.9.0 that you linked in issue #140. I'm now able to access the Tuneful settings again, and Spotify doesn't restart automatically when I quit it anymore so all fixed, thank you!

I went to #140, and I couldn't find any zip file V0.9.0. I am also experiencing this issue whenever I try to quit Spotify, it just keeps restarting.
