### ISSUE TITLE
battery drain

### ISSUE THREAD

**Issue by PrathamShetty26** [martinfekete10/Tuneful#142]
The device’s battery drains at a notably accelerated rate.
![Screenshot 2024-12-10 at 7 49 26 PM](https://github.com/user-attachments/assets/da2399f2-70d6-40b3-8d97-0067da8c500c)

**Comment by martinfekete10** [comment]
Are you using `Scrolling song info` in menu bar by any chance? If so, this is what's causing this issue. Thinking I'll disable the option until I optimize it so it doesn't drain the battery.
