### ISSUE TITLE
Tuneful Settings show an ep

### ISSUE THREAD

**Issue by SneaKy178** [martinfekete10/Tuneful#34]
![CleanShot 2023-12-14 at 22 08 35@2x](https://github.com/martinfekete10/Tuneful/assets/30359036/0e7ac2cd-f3e0-41d7-b319-e7e152528f4e)
See image

**Comment by martinfekete10** [comment]
Hi, what version of macOS are you using?

**Comment by SneaKy178** [comment]
Latest Mac Os Sonoma 14.2.1

**Comment by martinfekete10** [comment]
I just published a new release with all-new settings window and bunch of new features, expect it will resolve this issue as well - if not, feel free to re-open
