### ISSUE TITLE
Progress Bar and Play Time Not Updated

### ISSUE THREAD

**Issue by trufflepop** [martinfekete10/Tuneful#35]
**Description of bug:**
The song play time doesn't increase and the progress bar doesn't move as the song continues to play. They're only updated to the current time/position once the song is paused.

**Versions:**
Tuneful v0.9.6
macOS Sonoma 14.2

**Hardware:**
MacBook Pro M2 Pro (2023)

**Comment by martinfekete10** [comment]
Hi, can you provide more details about how to reproduce this issue? It seems to be working fine for me but there might be some edge case which triggers this behaviour

**Comment by smokinjoe2122** [comment]
I have this same issue. If you pause music, or perhaps pop out the mini player, the progress bar stops.

**Comment by seven-of-eleven** [comment]
Thanks for the great app. I've noted the same issue. Doesn't bother me much b/c I don't generally stare at the timer. Attached a video showing the behaviour. Same thing happens with the mini player.

#### Versions
Tuneful v0.9.6
MacOS Ventura 13.6.3

#### Hardware
MacPro 2019

https://github.com/martinfekete10/Tuneful/assets/76855829/981d5b28-d05e-47a8-a447-c9e14e6d0d08


Best.

**Comment by martinfekete10** [comment]
Interesting, is this happening every time the popover is opened? Is it happening after you quit and reopen application?

I still can't reproduce it on my machine, running macOS Sonoma on M1 Macbook Air.

**Comment by trufflepop** [comment]
The video seven-of-eleven posted is the same thing that happens to me. The pop-out mini player also behaves in the same way. 

There isn't really a specific trigger for the bug that I know of. The timestamp and progress bar have never worked for me.

**Comment by seven-of-eleven** [comment]
> Interesting, is this happening every time the popover is opened? Is it happening after you quit and reopen application?
> 
> I still can't reproduce it on my machine, running macOS Sonoma on M1 Macbook Air.

The timer doesn't move unless I pause the song. I can open the popover multiple times and the timer doesn't move. As soon as I pause the song it will jump to the location. Doesn't bother me much but if there's a way I can help to troubleshoot the issue let me know. Thanks.

**Comment by martinfekete10** [comment]
I managed to find the root cause and just released new version with a bunch of new features on top of this bugfix. Hope you will enjoy the new update!

**Comment by engeld** [comment]
Hey, this is still an issue at my side. I'm using Tuneful 1.1.0 with Spotify.

**Comment by engeld** [comment]
Here with a Screenshot to help visualize the issue - Song is about 0.50 second in and if I click on the song info of Tuneful in the menubar, it's giving me the no progress:

<img width="1356" alt="CleanShot 2024-01-13 at 20 03 37@2x" src="https://github.com/martinfekete10/Tuneful/assets/944746/37444cda-554d-47d8-9ce1-37eb39cfcb07">
