### ISSUE TITLE
Please add support for "Likes".

### ISSUE THREAD

**Issue by marknefedov** [martinfekete10/Tuneful#36]

**Comment by martinfekete10** [comment]
Hey, likes are currently supported for Apple Music. Spotify is a bit more complicated as there is a need to use Spotify API (unlike Apple Music, which supports likes through Scripting Bridge) which brings along a set of challanges, but I am definitely exploring implementing this in the future

**Comment by marknefedov** [comment]
Works with Apple Music, that is enough for me.
