### ISSUE TITLE
Doesn't work in full-screen apps w/ automatic menu bar hiding enabled

### ISSUE THREAD

**Issue by bilalnoork** [martinfekete10/Tuneful#38]
Works fine in full-screen apps without autohiding enabled.
Works fine on desktop with autohiding enabled/disabled.
However, in a full-screen app with autohiding enabled, the popup disappears as soon as you attempt to move the cursor down to interact with it, making Tuneful impossible to use.

**Comment by martinfekete10** [comment]
Hi, can you please post a video of the behaviour? Tried to replicate it but it worked fine for me

**Comment by bilalnoork** [comment]
https://github.com/martinfekete10/Tuneful/assets/52586835/e7058bfb-702c-4340-92bc-0198a9d6934c

**Comment by bilalnoork** [comment]
Bump. Also I should add that I am using Bartender, so I wonder if other people who use it have the same issue as this would be demonstrative of some sort of conflict between the two applications.

**Comment by bilalnoork** [comment]
I should add that any slight cursor movement in any direction after opening the Tuneful popup causes it to disappear, not just downward motion. Even moving to the right along the menu bar still causes the issue.

**Comment by bilalnoork** [comment]
My apologies, I am actually experiencing this issue with a variety of third-party menu applications (but not all). So, obviously the issue is on my end and not yours. I will leave an update if I figure out the root cause of the problem.
