### ISSUE TITLE
Doesn't start

### ISSUE THREAD

**Issue by bifi15** [martinfekete10/Tuneful#45]
Unfortunately, Tuneful does not start on my system (Mac mini M1, macOS 14.2.1)

**Comment by martinfekete10** [comment]
Can you please provide more details/screenshots? What happens when you click on the Tuneful icon in Launchpad?

**Comment by marknefedov** [comment]
Some windows tried to popup for fraction of a second, and app instantly closes.

**Comment by marknefedov** [comment]
[Tuneful-2024-01-13-010154.txt](https://github.com/martinfekete10/Tuneful/files/13924474/Tuneful-2024-01-13-010154.txt)

**Comment by marknefedov** [comment]
```
Last login: Sat Jan 13 00:59:22 on ttys000
/Applications/Tuneful.app/Contents/MacOS/Tuneful ; exit;
➜  ~ /Applications/Tuneful.app/Contents/MacOS/Tuneful ; exit;
Setting up music apps
2024-01-13 01:05:44.923 Tuneful[12645:671980] Can't find app with identifier com.spotify.client
The play state or the currently playing track changed
[1]    12645 trace trap  /Applications/Tuneful.app/Contents/MacOS/Tuneful

Saving session...completed.

[Process completed]
```

**Comment by marknefedov** [comment]
https://github.com/martinfekete10/Tuneful/assets/20001291/d0544132-88a0-4338-8d6d-d1da1fb004db

**Comment by martinfekete10** [comment]
@marknefedov Can you check what bundle ID does you Spotify app have? You can use this terminal command: `osascript -e 'id of app "Spotify"'`

@bifi15 Can you start the app from terminal and send me the output? In case it looks similarly to Mark's comment above, can you check the bundle ID as well? To start the app from terminal you can run this command: `/Applications/Tuneful.app/Contents/MacOS/Tuneful`

**Comment by marknefedov** [comment]
I don’t have Spotify. Looking a the video frame by frame, window that pops up is a selector between Apple Music and Spotify.

**Comment by det-box** [comment]
Habe leider das selbe Problem.
benutze kein Spotify
bei Eingabe von: B/Anwendungen/Tuneful.app/Inhalt/MacOS/Tuneful 

Einrichten von Musik-Apps 2024-01-13 10:46:36.095 Tuneful[2205:34841] Kann App mit Kennung com.spotify.client nicht finden Der Spielstatus oder der aktuell abgespielte Track hat sich geändert Trace/BPT-Falle: 5 MacBook-Pro-M2:~ detlef$ osascript -e 'id der App "Spotify"' 0:2: Ausführungsfehler: „Anwendung "Spotify"“ kann nicht gelesen werden. (-1728)

**Comment by martinfekete10** [comment]
Managed to found the root cause. I will publish a fixed version with a few new features today if all goes well 🙌

**Comment by martinfekete10** [comment]
[New version](https://github.com/martinfekete10/Tuneful/releases/tag/v1.1.0) that fixes this issue was just released 🎉

**Comment by det-box** [comment]
1.1.0 Works fine
Thanks
