### ISSUE TITLE
Trying to open preferences for the application causes an immediate crash

### ISSUE THREAD

**Issue by bilalnoork** [martinfekete10/Tuneful#46]
this happens no matter how i attempt to access the preferences, either thru the popup itself or by right clicking in the menu bar

https://github.com/martinfekete10/Tuneful/assets/52586835/47a97f02-e2cc-4a0a-a3d5-ab9172cf2a8e

**Comment by martinfekete10** [comment]
What version of macOS are you running?

**Comment by bilalnoork** [comment]
Sonoma 14.2.1

**Comment by trufflepop** [comment]
The same thing happens to me. Running Sonoma 14.2.1

**Comment by marknefedov** [comment]
Same behavior as #45

**Comment by martinfekete10** [comment]
Managed to found the root cause. I will publish a fixed version with a few new features today if all goes well 🙌

**Comment by martinfekete10** [comment]
[New version](https://github.com/martinfekete10/Tuneful/releases/tag/v1.1.0) that  fixes this issue was just released - you can download it from the Releases page or update Tuneful directly 🎉
