### ISSUE TITLE
Feature Request: Add support for homebrew

### ISSUE THREAD

**Issue by kDot** [martinfekete10/Tuneful#47]
Installation via homebrew would be super cool

**Comment by martinfekete10** [comment]
Thanks for great suggestion, I will try to implement it by the next release

**Comment by kannicht** [comment]
I already created a local brew cask file for Tuneful. 

I just had it been run through the audit process locally and the following message came up:

> audit for tuneful: failed
> - Signature verification failed:
>/private/tmp/cask-audit20240314-65593-1re2fd/Tuneful.app: rejected

>macOS on ARM requires software to be signed.
>Please contact the upstream developer to let them know they should sign and notarize their software.
>tuneful
>  * line 5, col 2: Signature verification failed:
>    /private/tmp/cask-audit20240314-65593-1re2fd/Tuneful.app: rejected
>
>    macOS on ARM requires software to be signed.
>    Please contact the upstream developer to let them know they should sign and notarize their software.

Additionally it reported that the upstream had Monterey as minimal requirement and not Ventura as mentioned in the README.

Any chance for a signed version? :)

**Comment by mayurankv** [comment]
Has there been any update on this? :)

**Comment by martinfekete10** [comment]
Yes! :) Tuneful is now available on homebrew using the following command: `brew install martinfekete10/tap/tuneful`

**Comment by SenseiMarv** [comment]
FYI: The Homebrew release is now replaced with the App Store version: https://github.com/martinfekete10/Tuneful/discussions/154#discussioncomment-11786220
