### ISSUE TITLE
Scrolling text and auto-hide

### ISSUE THREAD

**Issue by jonappleseed** [martinfekete10/Tuneful#49]
Please consider having song titles scroll horizontally if text is too long. Also option to hide text if the song is currently paused.

**Comment by martinfekete10** [comment]
Thanks for the great suggestions, will definitely consider implemeting them in the next update(s)!

**Comment by ncodee** [comment]
+1. Auto scroll media info would be nice.

**Comment by martinfekete10** [comment]
I just released a [new version](https://github.com/martinfekete10/Tuneful/releases/tag/v1.4.0) with these and several other new features, hope you will enjoy it  🙌
