### ISSUE TITLE
Song info and app-icon are overlapping in menubar

### ISSUE THREAD

**Issue by engeld** [martinfekete10/Tuneful#50]
Somehow the song info and app icon are overlapping in the menu bar and it's barely recognizable:
<img width="140" alt="CleanShot 2024-01-13 at 19 50 25@2x" src="https://github.com/martinfekete10/Tuneful/assets/944746/43d0e4a4-04a2-4645-9641-b0f6dc1f071c">

Those are the (default) settings which I did not change:
<img width="572" alt="CleanShot 2024-01-13 at 19 53 26@2x" src="https://github.com/martinfekete10/Tuneful/assets/944746/5b078538-4fe4-49a4-bdd8-b286e7274c30">

I'm using Tuneful 1.1.0 on macOS Monterey 12.7.2 @ MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)

**Comment by engeld** [comment]
When only either song info OR icon is enabled, then it's shown correctly. Only when both settings are enabled, then it seems like both the song info and the icon are overlaid. Maybe make sure that if both is enabled, then align them next to each other instead of the one on top of each other.

**Comment by martinfekete10** [comment]
Current implementation uses native element for text and image (`NSStatusBar.system.statusItem`). Are you using any kind of tool to customise menu bar appearance, e.g. spacing between items? I suspect that may be breaking the appearance

**Comment by martinfekete10** [comment]
I just released a [new version](https://github.com/martinfekete10/Tuneful/releases/tag/v1.4.0) which should resolve this bug, if it doesn't, feel free to reopen
