### ISSUE TITLE
Does "Heart" in the tuneful does same thing as "Star" in Apple Music?

### ISSUE THREAD

**Issue by marknefedov** [martinfekete10/Tuneful#51]
I've actually have a non-issue (I think?). Does "Heart" in the tuneful does same thing as "Star" in Apple Music (e.g Adding to Favorites playlist and library)? As currently I can't find where songs are added.
https://imgur.com/a/kUZzrPa

Also please consider enabling "Discussion" in addition to Issues.
https://docs.github.com/en/discussions

![Video](https://i.imgur.com/sjxIwhh.mp4)

**Comment by martinfekete10** [comment]
Interesting, this functionality was working a few months ago while I was developing it. Now that I'm loooking at it, Apple most likely changed the header files for Apple Music in the latest version which breaks it. I will look at it, hopefully will be able to fix it for the next release. And yes, heart in Tuneful "stars" song in Apple Music (probably will change the icon accordingly as well).

Thanks for suggesting Discussion, just added a poll there

**Comment by martinfekete10** [comment]
[New version](https://github.com/martinfekete10/Tuneful/releases/tag/v1.2.0) that fixes this issue was just released, it also introduces a new customisation features to popover and mini player window  🎉

**Comment by marknefedov** [comment]
Thank you, great!
But it looks like there is one more bug. 😅 
https://youtu.be/KiMsRJLIG4k 

"Unstaring" work only, when track is played from favorites playlist.
