### ISSUE TITLE
YouTube Music support

### ISSUE THREAD

**Issue by Suplanus** [martinfekete10/Tuneful#52]
Please add support for Apple Music 💖

**Comment by ncodee** [comment]
+1, would be a nice addition.

**Comment by martinfekete10** [comment]
Looked into this and there is unfortunately there is no way to integrate 3rd party service to YT Music. Managed to find one unofficial API, but it doesn't provide necessary endpoints to make even a fraction of functionality of Tuneful possible. Closing this issue for now, feel free to reopen if anything changes in this regard

**Comment by Suplanus** [comment]
Is it not possible to scrape from NotificationPlayer in the OS?
