### ISSUE TITLE
The following errors

### ISSUE THREAD

**Issue by netsrot69** [martinfekete10/Tuneful#57]
1. when I play a song, the progress bar does not continue.
2. the volume runs independently of the Mac system. Why?
3. i would like a close button in the display in the menu bar.
4. i can't find the MiniPlayer for the home screen. The app only runs from the menu bar.

**Comment by marknefedov** [comment]
Oooh, just checked, if Apple Music is playing on HomePods for example through airplay, and both pods and Mac are selected, only Mac volume is adjusted.

https://github.com/martinfekete10/Tuneful/assets/20001291/bcbe264f-ef39-45a6-907e-8af20a80e3eb


EDIT: Mac's system, volume is adjusted. Not the Apple Music one.

**Comment by marknefedov** [comment]
@netsrot69 Miniplayer is enabled with a toggle in the dropdown menu.
![Screenshot 2024-01-19 at 17 52 06@2x](https://github.com/martinfekete10/Tuneful/assets/20001291/b394e741-69eb-420e-a461-92f5209b222d)

**Comment by netsrot69** [comment]
Ah, ok, thanks... I had to search first until I found the right mouse click... 🙈

**Comment by marknefedov** [comment]
@martinfekete10 wouldn't it be better if Tuneful controlled Spotify/Music app volume instead of system Mac?

**Comment by martinfekete10** [comment]
Yeah I think it would be more consistent with the rest of the app. I'll probably push it in the next release, looks like it won't be too difficult to implement

**Comment by martinfekete10** [comment]
Just released a new version 1.3.0 that updates the volume control behaviour to adjust player volume instead of system volume (and introduces a new mini player design)  🎉 Closing this issue, if something else comes up, feel free to open a new one
