### ISSUE TITLE
Music play bar don't move when i'm playing music

### ISSUE THREAD

**Issue by froszbite1609** [martinfekete10/Tuneful#59]
<img width="220" alt="Screenshot 2567-01-22 at 18 22 35" src="https://github.com/martinfekete10/Tuneful/assets/115368268/5fe4662e-52be-49fb-82ca-ebcfc72ee6f0">

**Comment by marknefedov** [comment]
Are you using Spotify or Apple Music? Is this an Apple Music Radio by any chance?

**Comment by martinfekete10** [comment]
I just released a [new version](https://github.com/martinfekete10/Tuneful/releases/tag/v1.4.0) which should fix this bug - if it doesn't fix it, feel free to reopen the issue
