### ISSUE TITLE
Switch quickly between apple music and spotify

### ISSUE THREAD

**Issue by Seidon1984** [martinfekete10/Tuneful#63]
Hello everyone,

I would like to switch between apple music and spotify having an option when we right click instead of going to setting and change it. Also, it would be a good option to add the possibility to have a keyboard shortcut to switch between them or among then if in the future you add more music apps.

Great job, it is a fantastic app

**Comment by martinfekete10** [comment]
Hey, thanks for suggestions, both of them will be included in the next release (sometime this week)

**Comment by martinfekete10** [comment]
I just released a [new version](https://github.com/martinfekete10/Tuneful/releases/tag/v1.4.0) with these and several other new features 🙌
