### ISSUE TITLE
Ellipsis and left aligned menu bar content better

### ISSUE THREAD

**Issue by esreverse** [martinfekete10/Tuneful#69]
Heyhey, love the app. Two little bits of feedback

- I'd prefer to have a fixed non-animated text with ellipsis instead of the animation. a) because the animation is peripherally visible in the top right corner and b) because I have to wait to see the most important information: the artist and the beginning of the song title.
- I'd prefer to left align the content, not center it, since the empty space to the left looks like some invisible icon bug to me: https://share.cleanshot.com/pNjfL7rc

**Comment by DocSnyder0815** [comment]
I second the part about the option to disable the scrolling and to shorten the string with ellipsis if it not fits in the set width.

**Comment by martinfekete10** [comment]
Hey, just published v1.6.1 with new optino to disable animating menu bar text 🎉 I believe the second point was already fixed so closing this issue
