### ISSUE TITLE
[Feature Request] Option to switch off menu bar icon/album art icon, option to disable popover player

### ISSUE THREAD

**Issue by lothar-cell** [martinfekete10/Tuneful#70]
As the titles says, basically to be able to use the app for displaying text and nothing else.

**Comment by RomainCscn** [comment]
+1, @martinfekete10 could you consider this?

**Comment by martinfekete10** [comment]
Hey, feature to switch of icon/album art will be included in the next release! Expecting to release it in the next few days

**Comment by martinfekete10** [comment]
v1.6.0 was just released with this feature added, alongside several other new features and fixes 🙌

**Comment by lothar-cell** [comment]
Amazing, thank you very much, the new features are great! One small thing I noticed: currently the text stops moving only if the icon is visible, even if it fits to the pre-defined pixel width. An option to enable movement only when it's needed (when it doesn't fit), would refine things further.

**Comment by lothar-cell** [comment]
Also, if the pop-up player could be disabled as well, so only the text was displayed, and clicking on it was a shortcut to Spotify. This is also part of the original request.
