### ISSUE TITLE
Can't open app in macOS Sonoma

### ISSUE THREAD

**Issue by bidyutchanda** [martinfekete10/Tuneful#72]
After downloading the latest version and opening it on Sonoma, my system says "Tuneful can't be opened because Apple cannot check it for malicious software". Is there any workaround for this?

**Comment by martinfekete10** [comment]
Hi, are you talking about [this issue](https://support.apple.com/guide/mac-help/apple-cant-check-app-for-malicious-software-mchleab3a043/mac)? If yes, Tuneful can be opened by righ-clicking on app icon in Finder -> Open (this needs to be done only once).

Closing this issue, if it still fails for you, feel free to re-open.

**Comment by bidyutchanda** [comment]
Oops, sorry for such a dumb question. New to MacOS, actually. Thanks a lot.
