### ISSUE TITLE
More Customization Please!

### ISSUE THREAD

**Issue by JohnnyFireOne** [martinfekete10/Tuneful#79]
@martinfekete10 

The App is awesome! but can you consider more customization please? on menu popover player an option remove the buttons we don't need to make it clean and how we need to. (for example i love to have art, title, artist names and seekbar only) 
![Στιγμιότυπο οθόνης 1](https://github.com/martinfekete10/Tuneful/assets/136648679/0729ab3a-5406-4ef3-b081-c7ee56fc30eb)

and last at mini player an option to lock the placement and make it wider please!!!
![Στιγμιότυπο οθόνης](https://github.com/martinfekete10/Tuneful/assets/136648679/c94859db-115c-4d27-b6e2-b48663e94212)

thank you so much!
John.

**Comment by martinfekete10** [comment]
Hi John, today I released a new version of Tuneful with a new, minimalist popover option and also slightly updated the look of mini player

**Comment by JohnnyFireOne** [comment]
> Hi John, today I released a new version of Tuneful with a new, minimalist popover option and also slightly updated the look of mini player

@martinfekete10 

i tested and i totally!!! love it! i found a bug tho! when i select hidden or app icon at menu bar icon the sonf info details shrinks and moves even if i use 300 pixels at song info width, the only way to fix this and stay unmoved is to use album art at menu bar icon.

can you check this behaviour if you have time? beside that works great and the app feels smoother! thank you for you work!
