### ISSUE TITLE
Clicking on the menu bar doesn't toggle

### ISSUE THREAD

**Issue by robbiewxyz** [martinfekete10/Tuneful#80]
Love this app! This is a small ask; I might put up a PR if i get a chance.

MacOS's built in menus, as well as most apps', treat clicking on them in the menu bar as a toggle. If you click on the top bar menu once to open the menu or popover, clicking on the menu again closes the popover.

With Tuneful, clicking on the menubar again does a funny little glithy "hide and then reshow" thing.

Again a small thing. Thanks for the excellent app @-martinfekete10!

**Comment by robbiewxyz** [comment]
Oh the Swift code here looks super approachable.

This's probably as easy as [adjusting `showPopover`](https://github.com/martinfekete10/Tuneful/blob/main/Tuneful/Tuneful.swift#L347) to `togglePopover` and throwing in a little conditional to [check `popover.isShown`](https://developer.apple.com/documentation/appkit/nspopover/1535120-isshown).

**Comment by martinfekete10** [comment]
Hey, I just released a new version of Tuneful with your fix included, thank you very much :)
