### ISSUE TITLE
[Feature Request] Hide Menu Bar Icon

### ISSUE THREAD

**Issue by bengreeno** [martinfekete10/Tuneful#83]
It would be great to have the option for the Tuneful menu bar icon to be able to be hidden completely when music is not playing.

**Comment by mayurankv** [comment]
Or alternatively to be always hidden unless Tuneful is launched again! (many apps have this setting to not clutter the menu bar). This is useful for those of us who mainly use the media player!

**Comment by martinfekete10** [comment]
This feature will be a part of next release, expecting to publish it in the next few days

**Comment by martinfekete10** [comment]
v1.6.0 was just released with this feature added, alongside several other new features and fixes! :)

**Comment by bengreeno** [comment]
@martinfekete10 This is outstanding! Thank you!
