### ISSUE TITLE
I test the new version but...

### ISSUE THREAD

**Issue by JohnnyFireOne** [martinfekete10/Tuneful#87]
@martinfekete10 

I tested and i totally!!! love it! i found a bug tho! when i select hidden or app icon at menu bar icon the sonf info details shrinks and moves even if i use 300 pixels at song info width, the only way to fix this and stay unmoved is to use album art at menu bar icon.
The show song info I menu bar whe it's on when playing keep showing up open Apple Music when not supposed to, needs to be hidden. The workaround I use is the pause the Apple Music and quit it then it stays hidden, if I quit Apple Music without pause stays at menu open and says open Apple Music.

can you check this behaviour if you have time? beside that works great and the app feels smoother! thank you for you work!

**Comment by martinfekete10** [comment]
Thanks for reporting, found a root cause and will release a new version soon

**Comment by JohnnyFireOne** [comment]
> Thanks for reporting, found a root cause and will release a new version soon

You are the best!!!!!!!!!

**Comment by martinfekete10** [comment]
New version was just released 🎉

**Comment by JohnnyFireOne** [comment]
> New version was just released 🎉 

Hellyeah!!! I will test it soon as I get home! And I will report if I find any other issue!

**Comment by JohnnyFireOne** [comment]
@martinfekete10  
 I test the new version and works!

The only issue I have is when I quit Apple Music the menu show a text open Apple Music.

When I pause the Apple Music and the quit the message stays hidden. 

Can you fix that too please?
