### ISSUE TITLE
Option to disable Popover player

### ISSUE THREAD

**Issue by lothar-cell** [martinfekete10/Tuneful#91]
Since the built-in one in Control Centre/Menu Bar does this already, it's a bit confusing to have two player controls in the same time, also I'm using an app called Sleeve, which can display big album art on the desktop. Also I guess it would use less memory when the app runs in the background? (although I'm not sure)

Due to these, for me the Popover is more of a distraction and it would be more useful, if clicking to the info text activated Spotify window instead.

**Comment by martinfekete10** [comment]
Thanks for suggestion, I'll be implementing this feature in the next release - should be out sometime this week

**Comment by martinfekete10** [comment]
Just released a new version with this feature (and bunch of others) implemented 🎉
