### ISSUE TITLE
Blank Window on launch

### ISSUE THREAD

**Issue by rennaMAhcuS** [martinfekete10/Tuneful#94]
The launch of the application triggers the opening of a blank window, which appears like this:

<img width="961" alt="image" src="https://github.com/user-attachments/assets/1fd132ef-b21d-4311-93e8-355a6d26d834">

This window is unnecessary. It usually doesn't happen, but it started when I updated my device.

**Comment by rennaMAhcuS** [comment]
Also, the status of **`shuffle`** and **`loop`** may not be correct (**synced**) when initialized, i.e., when bot **Spotify** and **Tuneful** are started.

**Comment by JohnnyFireOne** [comment]
i have this as well using macOS 15 beta 2 but, sometimes i show that in sonoma latest too

**Comment by det-box** [comment]
For me also in macOS 15

**Comment by martinfekete10** [comment]
I just managed to fix this issue (caused by 3rd party dependency), update is now available to download :)

**Comment by rennaMAhcuS** [comment]
Yeah! The issue is gone...🥳🥳!

**Comment by det-box** [comment]
Thank you,
You are the best!
